language: cpp
compiler: gcc
env: NLTK_PTB_DP_FILE=$PWD/nltk_data/corpora/dependency_treebank/nltk-ptb.dp LIMA_DIST=$PWD/dist
  LIMA_CONF=$LIMA_DIST/share/config/lima LIMA_RESOURCES=$LIMA_DIST/share/apps/lima/resources
  PATH=$LIMA_DIST/bin:$LIMA_DIST/share/apps/lima/scripts:$PATH LD_LIBRARY_PATH=$LIMA_DIST/lib
install:
  - cat /etc/*-release
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libboost1.48-all-dev  libenchant-dev python-nltk gawk qt5-qmake qtbase5-dev
  - sudo sed -ie "s|DEFAULT_URL = 'http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml'|DEFAULT_URL = 'http://nltk.github.com/nltk_data/'|" /usr/lib/python2.7/*/nltk/downloader.py
  - python -m nltk.downloader -d nltk_data dependency_treebank
  - cat nltk_data/corpora/dependency_treebank/wsj_*.dp | grep -v "^$" > nltk_data/corpora/dependency_treebank/nltk-ptb.dp
script: mkdir dist && mkdir build && cd build && cmake -DLIMA_RESOURCES:STRING=build
  -DCMAKE_INSTALL_PREFIX:PATH=$ENV{LIMA_DIST} -DCMAKE_BUILD_TYPE:STRING=Release ..
  && make -j4 
after_success:
  - pushd $LIMA_DIST/share/apps/lima/tests
  - tva --language=eng test-eng.*.xml 2>&1 | tee tva-eng.log
  - tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml 2>&1 | tee tva-fre.log
  - "curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_common-prefix/src/lima_common-build/limacommon-1.0.0-Linux.deb sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_linguisticprocessing-prefix/src/lima_linguisticprocessing-build/limalinguisticprocessing-1.0.0-Linux.deb sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_linguisticdata-prefix/src/lima_linguisticdata-build/limadata.deb sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_annoqt-prefix/src/lima_annoqt-build/limaannoqt-1.0.0-Linux.deb sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T /home/travis/build/aymara/lima/build/lima_pelf-prefix/src/lima_pelf-build/limapelf-1.0.0-Linux.tar.gz sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T $LIMA_DIST/share/apps/lima/tests/tva-eng.log sftp://kleag@download.gna.org/upload/aymara-lima/"
  - "curl --ftp-create-dirs -T $LIMA_DIST/share/apps/lima/tests/tva-fre.log sftp://kleag@download.gna.org/upload/aymara-lima/"
